/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        light: {
          text: '#333333',
          subtext: '#888888',
          background: '#5497B8',
          headerBg: '#5497B8',
          icon: '#333333',
          primaryAccent: '#A8E6CF',
          secondaryAccent: '#DCB2FF',
          tertiaryAccent: '#A0D9FF',
          success: '#A5D6A7',
          warning: '#FFD54F',
          danger: '#FF6B6B',
          border: '#E0E0E0',
          card: '#FFFFFF',
          listItem: '#C8DAE3',
        },
        dark: {
          text: '#E0E0E0',
          subtext: '#A0A0A0',
          background: '#17212B',
          headerBg: '#232E3C',
          icon: '#F1F5F9',
          primaryAccent: '#7ED9B0',
          secondaryAccent: '#B88BFF',
          tertiaryAccent: '#7AC0E8',
          success: '#C8E6C9',
          warning: '#FFEB3B',
          danger: '#FF8A80',
          border: '#4A5568',
          card: '#3A506B',
          buttonBg1: '#5288C1',
          listItem: '#232E3C',
        },
      },
    },
  },
  plugins: [],
};
