export const APP_PERMISSIONS = {
  // Subscription Management
  SUBSCRIPTOINS_VIEW: "subscriptions:view",

  // Plans Management
  PLANS_VIEW: "plans:view",
  PLANS_CREATE: "plans:create",
  PLANS_EDIT: "plans:edit",
  PLANS_CHANGE_STATUS: "plans:change_status",
  PLANS_DELETE: "plans:delete",

  // User Management (Users)
  USERS_VIEW: "users:view",
  USERS_CREATE: "users:create",
  USERS_EDIT: "users:edit",
  USERS_CHANGE_STATUS: "users:change_status",
  USERS_DELETE: "users:delete",

  // Vendor Management
  VENDORS_VIEW: "vendors:view",
  VENDORS_CREATE: "vendors:create",
  VENDORS_EDIT: "vendors:edit",
  VENDORS_DELETE: "vendors:delete",
  VENDORS_CHANGE_STATUS: "vendors:change_status",
  VENDORS_VIEW_AGENTS: "vendors:view_agents",
  VENDORS_ACTIVATE: "vendors:activate_vendor",

  // Agent Management
  AGENTS_CREATE: "agents:create",
  AGENTS_EDIT: "agents:edit",
  AGENTS_CHANGE_STATUS: "agents:change_status",
  AGENTS_DELETE: "agents:delete",

  // Affiliate Management
  AFFILIATES_VIEW: "affiliates:view",
  AFFILIATES_CREATE: "affiliates:create",
  AFFILIATES_EDIT: "affiliates:edit",
  AFFILIATES_CHANGE_STATUS: "affiliates:change_status",
  AFFILIATES_DELETE: "affiliates:delete",
  AFFILIATES_ACTIVATE: "vendors:activate_affiliate",

  // Coupon Code Management
  COUPONS_VIEW: "coupons:view",
  COUPONS_APPROVE: "coupons:approve",

  // Commissions Management
  COMMISSIONS_VIEW: "commissions:view",
  COMMISSIONS_PAY: "commissions:pay",

  // Contacts Management
  CONTACTS_VIEW: "contacts:view",
  VIEW_VENDOR_CONTACTS: "contacts:view_vendor_contacts",

  // Template Management
  TEMPLATES_VIEW: "templates:view",

  // Exports Management
  EXPORTS: "data:export_data",
};

export const ROLE_PERMISSIONS = {
  1: [...Object.values(APP_PERMISSIONS)],
  2: [
    APP_PERMISSIONS.SUBSCRIPTOINS_VIEW,

    APP_PERMISSIONS.PLANS_VIEW,
    APP_PERMISSIONS.PLANS_CREATE,
    APP_PERMISSIONS.PLANS_EDIT,
    APP_PERMISSIONS.PLANS_CHANGE_STATUS,

    APP_PERMISSIONS.USERS_VIEW,
    APP_PERMISSIONS.USERS_CREATE,
    APP_PERMISSIONS.USERS_EDIT,
    APP_PERMISSIONS.USERS_CHANGE_STATUS,

    APP_PERMISSIONS.VENDORS_VIEW,
    APP_PERMISSIONS.VENDORS_CREATE,
    APP_PERMISSIONS.VENDORS_EDIT,
    APP_PERMISSIONS.VENDORS_CHANGE_STATUS,
    APP_PERMISSIONS.VENDORS_VIEW_AGENTS,
    APP_PERMISSIONS.VENDORS_ACTIVATE,

    APP_PERMISSIONS.AGENTS_CREATE,
    APP_PERMISSIONS.AGENTS_EDIT,
    APP_PERMISSIONS.AGENTS_CHANGE_STATUS,

    APP_PERMISSIONS.AFFILIATES_VIEW,
    APP_PERMISSIONS.AFFILIATES_CREATE,
    APP_PERMISSIONS.AFFILIATES_EDIT,
    APP_PERMISSIONS.AFFILIATES_CHANGE_STATUS,
    APP_PERMISSIONS.AFFILIATES_ACTIVATE,

    APP_PERMISSIONS.COUPONS_VIEW,
    APP_PERMISSIONS.COUPONS_APPROVE,

    APP_PERMISSIONS.COMMISSIONS_VIEW,
    APP_PERMISSIONS.COMMISSIONS_PAY,

    APP_PERMISSIONS.CONTACTS_VIEW,
    APP_PERMISSIONS.VIEW_VENDOR_CONTACTS,

    APP_PERMISSIONS.TEMPLATES_VIEW,

    APP_PERMISSIONS.EXPORTS,
  ],
  3: [
    APP_PERMISSIONS.SUBSCRIPTOINS_VIEW,
    APP_PERMISSIONS.PLANS_VIEW,
    APP_PERMISSIONS.USERS_VIEW,
    APP_PERMISSIONS.VENDORS_VIEW,
    APP_PERMISSIONS.VENDORS_VIEW_AGENTS,
    APP_PERMISSIONS.AFFILIATES_VIEW,
    APP_PERMISSIONS.COUPONS_VIEW,
    APP_PERMISSIONS.COMMISSIONS_VIEW,
    APP_PERMISSIONS.CONTACTS_VIEW,
    APP_PERMISSIONS.VIEW_VENDOR_CONTACTS,
    APP_PERMISSIONS.TEMPLATES_VIEW,
    APP_PERMISSIONS.EXPORTS,
  ],
  4: [
    APP_PERMISSIONS.SUBSCRIPTOINS_VIEW,
    APP_PERMISSIONS.PLANS_VIEW,
    APP_PERMISSIONS.USERS_VIEW,
    APP_PERMISSIONS.VENDORS_VIEW,
    APP_PERMISSIONS.VENDORS_VIEW_AGENTS,
    APP_PERMISSIONS.AFFILIATES_VIEW,
    APP_PERMISSIONS.COUPONS_VIEW,
    APP_PERMISSIONS.COMMISSIONS_VIEW,
    APP_PERMISSIONS.CONTACTS_VIEW,
    APP_PERMISSIONS.VIEW_VENDOR_CONTACTS,
    APP_PERMISSIONS.TEMPLATES_VIEW,
  ],
};
